### ISSUE TITLE
Need to setup an issue tracking tool

### ISSUE THREAD

**Issue by malintha** [fontman/fontman.github.io#1]
Good if we can have it prior the global release.
E.g.: JIRA, bugzilla etc.

**Comment by pathumego** [comment]
@Malintha whay cant we stick with GitHub issues?

**Comment by pathumego** [comment]
@Malintha github Projects interface can handle multiple repos kanban style. not enough?

**Comment by malintha** [comment]
@pathumego Agree. I was thinking the same. Lets stick to this till we get any requirement. :)
